export const books = [
  {
    title: 'Володар перснів: Хранителі Персня',
    author: 'Дж. Р. Р. Толкін',
    year: 1954,
    genre: 'Фентезі',
    available: true,
    image: 'https://covers.openlibrary.org/b/id/8231990-L.jpg',
  },
  {
    title: 'Володар перснів: Дві вежі',
    author: 'Дж. Р. Р. Толкін',
    year: 1954,
    genre: 'Фентезі',
    available: true,
    image: 'https://covers.openlibrary.org/b/id/8231991-L.jpg',
  },
  {
    title: 'Гаррі Поттер і філософський камінь',
    author: 'Дж. К. Ролінґ',
    year: 1997,
    genre: 'Фентезі',
    available: false,
    image: 'https://covers.openlibrary.org/b/id/7888782-L.jpg',
  },
  {
    title: 'Гаррі Поттер і Таємна кімната',
    author: 'Дж. К. Ролінґ',
    year: 1998,
    genre: 'Фентезі',
    available: true,
    image: 'https://covers.openlibrary.org/b/id/8221256-L.jpg',
  },
  {
    title: '1984',
    author: 'Джордж Орвелл',
    year: 1949,
    genre: 'Антиутопія',
    available: true,
    image: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  },
  {
    title: 'Колгосп тварин',
    author: 'Джордж Орвелл',
    year: 1945,
    genre: 'Антиутопія',
    available: true,
    image: 'https://covers.openlibrary.org/b/id/10392578-L.jpg',
  },
  {
    title: 'Маленький принц',
    author: 'Антуан де Сент-Екзюпері',
    year: 1943,
    genre: 'Філософська казка',
    available: true,
    image: 'https://covers.openlibrary.org/b/id/8750196-L.jpg',
  },
  {
    title: 'Нічний політ',
    author: 'Антуан де Сент-Екзюпері',
    year: 1931,
    genre: 'Роман',
    available: true,
    image: 'https://covers.openlibrary.org/b/id/11083896-L.jpg',
  },
  {
    title: 'Майстер і Маргарита',
    author: 'Михайло Булгаков',
    year: 1967,
    genre: 'Роман',
    available: true,
    image: 'https://covers.openlibrary.org/b/id/11260589-L.jpg',
  },
  {
    title: 'Собаче серце',
    author: 'Михайло Булгаков',
    year: 1925,
    genre: 'Сатирична повість',
    available: false,
    image: 'https://covers.openlibrary.org/b/id/10521280-L.jpg',
  },
];
